// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH24zecrMlarpPB5vt1Kp-TuBzdeE0LDg',
    appId: '1:832351300327:web:11396e7f1c450091fcd042',
    messagingSenderId: '832351300327',
    projectId: 'shindrachat',
    authDomain: 'shindrachat.firebaseapp.com',
    databaseURL: 'https://shindrachat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shindrachat.appspot.com',
    measurementId: 'G-GV3JL9FPLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJ8Q1uckCnk3lMC1hVkskqXUnEtfwdo0',
    appId: '1:832351300327:android:a83f9ca65fe61d82fcd042',
    messagingSenderId: '832351300327',
    projectId: 'shindrachat',
    databaseURL: 'https://shindrachat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shindrachat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oWyLBBgASw1nvtU3HlbvrXUvSRd43BA',
    appId: '1:832351300327:ios:723fd8adc4144293fcd042',
    messagingSenderId: '832351300327',
    projectId: 'shindrachat',
    databaseURL: 'https://shindrachat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shindrachat.appspot.com',
    iosBundleId: 'com.example.shindrachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oWyLBBgASw1nvtU3HlbvrXUvSRd43BA',
    appId: '1:832351300327:ios:cfc84565e884cfebfcd042',
    messagingSenderId: '832351300327',
    projectId: 'shindrachat',
    databaseURL: 'https://shindrachat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shindrachat.appspot.com',
    iosBundleId: 'com.example.shindrachat.RunnerTests',
  );
}
